# Generated by Django 5.2.1 on 2025-05-31 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='kg',
            field=models.DecimalField(choices=[(0.5, '0.5 kg'), (1.0, '1 kg'), (1.5, '1.5 kg'), (2.0, '2 kg'), (2.5, '2.5 kg'), (3.0, '3 kg'), (3.5, '3.5 kg'), (4.0, '4 kg'), (4.5, '4.5 kg'), (5.0, '5 kg')], decimal_places=1, default=1.0, max_digits=2),
        ),
    ]
