# Generated by Django 5.2.1 on 2025-05-31 17:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='kg',
            field=models.DecimalField(choices=[(Decimal('0.5'), '0.5 kg'), (Decimal('1'), '1 kg'), (Decimal('1.5'), '1.5 kg'), (Decimal('2'), '2 kg'), (Decimal('2.5'), '2.5 kg'), (Decimal('3'), '3 kg'), (Decimal('3.5'), '3.5 kg'), (Decimal('4'), '4 kg'), (Decimal('4.5'), '4.5 kg'), (Decimal('5'), '5 kg')], decimal_places=1, default=1.0, max_digits=3),
        ),
    ]
