# Generated by Django 5.2.1 on 2025-06-03 14:09

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_kg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='kg',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kg', models.DecimalField(choices=[(Decimal('0.5'), '0.5 kg'), (Decimal('1'), '1 kg'), (Decimal('1.5'), '1.5 kg'), (Decimal('2'), '2 kg'), (Decimal('2.5'), '2.5 kg'), (Decimal('3'), '3 kg'), (Decimal('3.5'), '3.5 kg'), (Decimal('4'), '4 kg'), (Decimal('4.5'), '4.5 kg'), (Decimal('5'), '5 kg')], decimal_places=1, max_digits=3)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
        ),
    ]
