# Generated by Django 5.2.1 on 2025-06-07 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flavour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('classic', 'Classics'), ('chocolate', 'Chocolates'), ('fruity', 'Fruity')], max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='flavour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.flavour'),
        ),
    ]
