# Generated by Django 5.2.1 on 2025-05-25 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_system', '0002_remove_order_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
