# Generated by Django 5.2.1 on 2025-05-31 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_system', '0006_remove_order_delivery_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
    ]
