# Generated by Django 5.2.1 on 2025-06-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_system', '0007_remove_order_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='No address provided', max_length=255),
            preserve_default=False,
        ),
    ]
