# Generated by Django 5.2.1 on 2025-06-03 14:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_system', '0008_order_address'),
        ('products', '0004_remove_product_kg_remove_product_price_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderproduct',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='kg',
            field=models.DecimalField(choices=[(Decimal('0.5'), '0.5 kg'), (Decimal('1'), '1 kg'), (Decimal('1.5'), '1.5 kg'), (Decimal('2'), '2 kg'), (Decimal('2.5'), '2.5 kg'), (Decimal('3'), '3 kg'), (Decimal('3.5'), '3.5 kg'), (Decimal('4'), '4 kg'), (Decimal('4.5'), '4.5 kg'), (Decimal('5'), '5 kg')], decimal_places=1, default='0.5', max_digits=3),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='orderproduct',
            unique_together={('order', 'product', 'kg')},
        ),
    ]
