# Generated by Django 5.2.1 on 2025-06-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_system', '0009_alter_orderproduct_unique_together_orderproduct_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('UBER', 'Uber'), ('PICKUP', 'Pickup')], default='UBER', max_length=10),
        ),
    ]
